/**
 * Exhibit 5 — Statistical Output Quality Tests
 * Runs simplified NIST SP 800-22 tests on all three DRBGs.
 */

import { hmacDrbgInstantiate, hmacDrbgGenerate } from '../crypto/hmac-drbg';
import { ctrDrbgInstantiate, ctrDrbgGenerate } from '../crypto/ctr-drbg';
import { hashDrbgInstantiate, hashDrbgGenerate } from '../crypto/hash-drbg';
import { getRandomEntropy } from '../crypto/utils';
import { runAllTests } from '../stats/nist-tests';


/**
 * A deliberately-broken generator: a linear congruential generator (LCG), the
 * same family behind Math.random(). Its low bits are highly non-random, so
 * painting the bytes reveals visible diagonal banding. This is an HONEST bad
 * example — we are showing real LCG output, not a faked pattern.
 *
 * Constants are the classic MINSTD (Park–Miller) multiplier; we take the top
 * byte of each state so the structure is visible at a glance.
 */
function lcgBytes(n: number): Uint8Array {
  const out = new Uint8Array(n);
  let s = 1234567 >>> 0;
  for (let i = 0; i < n; i++) {
    s = (Math.imul(s, 16807) + 12345) >>> 0;
    out[i] = (s >>> 24) & 0xff;
  }
  return out;
}

/** Paint a 64x64 canvas: one output byte per pixel as a greyscale value. */
function paintGrid(canvas: HTMLCanvasElement | null, bytes: Uint8Array): void {
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const w = canvas.width;
  const h = canvas.height;
  const img = ctx.createImageData(w, h);
  for (let i = 0; i < w * h; i++) {
    const v = bytes[i] ?? 0;
    img.data[i * 4] = v;
    img.data[i * 4 + 1] = v;
    img.data[i * 4 + 2] = v;
    img.data[i * 4 + 3] = 255;
  }
  ctx.putImageData(img, 0, 0);
}

export function buildExhibit5(announce: (msg: string) => void): HTMLElement {
  const section = document.createElement('section');
  section.className = 'exhibit';
  section.setAttribute('aria-labelledby', 'exhibit5-title');

  section.innerHTML = `
    <h2 class="exhibit-title" id="exhibit5-title">Exhibit 5 — Statistical Output Quality</h2>
    <div class="exhibit-body">
      <div class="panel">
        <div class="panel-header"><span aria-hidden="true">📈</span> Statistical Output Quality (Simplified)</div>
        <p style="font-size:0.85rem;line-height:1.7;color:var(--text-secondary)">
          Three simplified NIST SP 800-22 tests, plus a Shannon-entropy estimate,
          run on 1,024 bytes generated by each DRBG:
        </p>
        <ol style="list-style:decimal;padding-left:1.5rem;font-size:0.85rem;color:var(--text-secondary);line-height:1.7" role="list">
          <li><strong style="color:var(--text-primary)">Frequency (Monobit)</strong> — proportion of 0s and 1s ≈ 50/50 <span style="color:var(--text-muted)">(SP 800-22 §2.1)</span></li>
          <li><strong style="color:var(--text-primary)">Runs Test</strong> — uninterrupted sequences of identical bits <span style="color:var(--text-muted)">(SP 800-22 §2.3)</span></li>
          <li><strong style="color:var(--text-primary)">Longest Run of Ones</strong> — longest consecutive run of 1s <span style="color:var(--text-muted)">(SP 800-22 §2.4)</span></li>
          <li><strong style="color:var(--text-primary)">Shannon Entropy</strong> — entropy of the byte distribution <span style="color:var(--text-muted)">(not part of SP 800-22)</span></li>
        </ol>
        <p style="font-size:0.78rem;line-height:1.6;color:var(--text-muted);margin:0">
          These are teaching-grade approximations (e.g. the p-values use closed-form
          estimates). The full SP 800-22 battery has 15 tests and needs far more data —
          the point here is the lesson below, not a production randomness audit.
        </p>
        <div class="controls-row" style="margin-top:0.75rem">
          <button class="btn btn-primary" id="stat-run-all" aria-label="Run all statistical tests on all three DRBGs">Test All Three DRBGs</button>
        </div>
      </div>

      <div id="stat-results" style="display:none">
        <div class="panel" id="stat-table-panel">
          <div class="panel-header"><span aria-hidden="true">✅</span> Results</div>
          <div style="overflow-x:auto">
            <table class="cmp-table" id="stat-table" aria-label="Statistical test results for all DRBGs">
              <thead>
                <tr>
                  <th scope="col">Test</th>
                  <th scope="col">HMAC_DRBG</th>
                  <th scope="col">CTR_DRBG</th>
                  <th scope="col">Hash_DRBG</th>
                </tr>
              </thead>
              <tbody id="stat-tbody"></tbody>
            </table>
          </div>
        </div>

        <div class="panel">
          <div class="panel-header"><span aria-hidden="true">📊</span> Shannon Entropy Comparison</div>
          <p style="font-size:0.78rem;line-height:1.6;color:var(--text-muted);margin:0">
            All three bars sit at essentially <strong style="color:var(--text-primary)">8.00 bits/byte</strong> — the
            maximum. That is the point: good generators are <em>indistinguishable</em> here.
            A taller bar would <strong style="color:var(--text-primary)">not</strong> mean "more secure";
            a much <em>shorter</em> one would just flag an obviously broken generator.
          </p>
          <div class="bar-chart" id="entropy-chart" role="img" aria-label="Bar chart comparing Shannon entropy across DRBGs"></div>
        </div>

        <div class="panel">
          <div class="panel-header"><span aria-hidden="true">🟩</span> What Random <em>Looks</em> Like</div>
          <p style="font-size:0.85rem;line-height:1.7;color:var(--text-secondary);margin:0">
            Each pixel is one output byte painted as a greyscale value (00 = black, FF = white).
            The DRBG grid on the left is snow; the broken generator on the right —
            a textbook <strong style="color:var(--text-primary)">linear congruential generator (LCG)</strong>,
            the family behind <code style="font-family:var(--font-mono)">Math.random()</code> — shows
            visible diagonal banding. Your eye catches the LCG instantly.
          </p>
          <div class="pixel-grids">
            <div class="pixel-cell">
              <canvas id="pixel-drbg" width="64" height="64"
                      role="img" aria-label="64 by 64 grid of HMAC_DRBG output bytes as greyscale pixels: no visible pattern, looks like random snow"></canvas>
              <span class="pixel-caption"><strong>HMAC_DRBG</strong> — passes "looks random"</span>
            </div>
            <div class="pixel-cell">
              <canvas id="pixel-lcg" width="64" height="64"
                      role="img" aria-label="64 by 64 grid of linear congruential generator output bytes as greyscale pixels: clear diagonal banding, obviously not random"></canvas>
              <span class="pixel-caption"><strong>Broken LCG</strong> — visible diagonal structure</span>
            </div>
          </div>
          <p style="font-size:0.78rem;line-height:1.6;color:var(--text-muted);margin:0">
            But "looks random" is a floor, not a ceiling. A backdoored generator like
            Dual_EC produces a grid that looks <em>exactly</em> as clean as HMAC_DRBG's —
            the eye and the tests both pass it. Structure you can see is the <em>easy</em>
            failure to catch.
          </p>
        </div>
      </div>

      <div class="panel" id="stat-dualec-panel" style="display:none">
        <div class="panel-header" style="color:var(--red-corrupt)"><span aria-hidden="true">⚠️</span> Versus Dual_EC_DRBG</div>
        <p style="font-size:0.85rem;line-height:1.7;color:var(--text-secondary)">
          Simulated Dual_EC_DRBG output also <strong style="color:var(--text-primary)">passes all four tests</strong>.
          Statistical tests catch broken DRBGs (like a PRNG seeded with a constant) but
          <strong style="color:var(--red-corrupt)">cannot detect a mathematically sound backdoor</strong>.
          The Dual_EC backdoor is undetectable by statistical analysis — it only helps
          the party who knows the discrete log relationship between P and Q.
        </p>
        <p style="font-size:0.8rem;line-height:1.6;color:var(--text-primary);border:1px solid var(--amber-warn);border-radius:6px;padding:0.6rem 0.75rem;background-color:rgba(255,170,0,0.06)">
          <strong>Honest disclosure:</strong> we can't run real Dual_EC_DRBG in a browser, so
          this row uses OS randomness (<code style="font-family:var(--font-mono)">crypto.getRandomValues</code>)
          as a stand-in. That is deliberate, not a cheat: the whole lesson is that
          <strong>clean-looking output tells you nothing about a hidden trapdoor</strong>. The stand-in
          passes exactly as the real backdoored generator did — which is the point.
        </p>
        <div style="overflow-x:auto">
          <table class="cmp-table" id="dualec-table" aria-label="Dual EC DRBG statistical test results">
            <thead>
              <tr><th scope="col">Test</th><th scope="col">Simulated Dual_EC</th><th scope="col">Status</th></tr>
            </thead>
            <tbody id="dualec-tbody"></tbody>
          </table>
        </div>
        <p style="font-size:0.85rem;margin-top:0.75rem">
          <a href="https://systemslibrarian.github.io/crypto-lab-corrupted-oracle/"
             target="_blank" rel="noopener noreferrer"
             style="color:var(--blue-info);text-decoration:underline">
            See the attack demonstrated in Corrupted Oracle →<span class="sr-only"> (opens in new tab)</span>
          </a>
        </p>
      </div>

      <div class="callout" role="note">
        <strong>Why this matters:</strong> Statistical tests catch broken DRBGs (like a PRNG
        seeded with a constant) but cannot detect a mathematically sound backdoor. This is
        exactly why algorithm choice and standard compliance matter — not just output quality
        checks. A backdoored DRBG passes every statistical test by design.
      </div>
    </div>
  `;

  requestAnimationFrame(() => wireExhibit5(section, announce));
  return section;
}

function wireExhibit5(section: HTMLElement, announce: (msg: string) => void): void {
  const runBtn = section.querySelector<HTMLButtonElement>('#stat-run-all')!;
  const resultsDiv = section.querySelector<HTMLElement>('#stat-results')!;
  const dualecPanel = section.querySelector<HTMLElement>('#stat-dualec-panel')!;

  runBtn.addEventListener('click', async () => {
    runBtn.disabled = true;
    runBtn.textContent = 'Running tests...';
    announce('Running statistical tests on all three DRBGs');

    try {
      const TEST_BYTES = 1024;

      // Generate 1024 bytes from each DRBG
      const hmacEntropy = getRandomEntropy(32);
      const hmacNonce = getRandomEntropy(16);
      const hmacState = await hmacDrbgInstantiate(hmacEntropy, hmacNonce);
      const hmacResult = await hmacDrbgGenerate(hmacState, TEST_BYTES);

      const ctrEntropy = getRandomEntropy(48);
      const ctrState = await ctrDrbgInstantiate(ctrEntropy);
      const ctrResult = await ctrDrbgGenerate(ctrState, TEST_BYTES);

      const hashEntropy = getRandomEntropy(55);
      const hashNonce = getRandomEntropy(16);
      const hashState = await hashDrbgInstantiate(hashEntropy, hashNonce);
      const hashResult = await hashDrbgGenerate(hashState, TEST_BYTES);

      // Run tests
      const hmacTests = runAllTests(hmacResult.output);
      const ctrTests = runAllTests(ctrResult.output);
      const hashTests = runAllTests(hashResult.output);

      // Build results table
      const tbody = section.querySelector<HTMLElement>('#stat-tbody')!;
      tbody.innerHTML = '';

      for (let i = 0; i < hmacTests.length; i++) {
        const tr = document.createElement('tr');
        tr.innerHTML = `
          <td>${hmacTests[i]!.name}</td>
          <td class="${hmacTests[i]!.passed ? 'stat-pass' : 'stat-fail'}">
            ${hmacTests[i]!.passed ? 'PASS' : 'FAIL'} (${hmacTests[i]!.pValue})
          </td>
          <td class="${ctrTests[i]!.passed ? 'stat-pass' : 'stat-fail'}">
            ${ctrTests[i]!.passed ? 'PASS' : 'FAIL'} (${ctrTests[i]!.pValue})
          </td>
          <td class="${hashTests[i]!.passed ? 'stat-pass' : 'stat-fail'}">
            ${hashTests[i]!.passed ? 'PASS' : 'FAIL'} (${hashTests[i]!.pValue})
          </td>
        `;
        tbody.appendChild(tr);
      }

      // Shannon entropy bar chart
      const chart = section.querySelector<HTMLElement>('#entropy-chart')!;
      chart.innerHTML = '';
      const entropies = [
        { label: 'HMAC_DRBG', value: hmacTests[3]!.pValue, color: 'var(--green-clean)' },
        { label: 'CTR_DRBG', value: ctrTests[3]!.pValue, color: 'var(--blue-info)' },
        { label: 'Hash_DRBG', value: hashTests[3]!.pValue, color: 'var(--amber-warn)' },
      ];

      for (const e of entropies) {
        const col = document.createElement('div');
        col.className = 'bar-col';
        const heightPct = Math.min(e.value * 100, 100);
        col.innerHTML = `
          <div class="bar" style="height:${heightPct}%;background-color:${e.color}" role="presentation"></div>
          <div class="bar-label">${e.label}<br>${(e.value * 8).toFixed(2)} b/B</div>
        `;
        chart.appendChild(col);
      }

      // Update chart aria-label with actual values for screen readers
      const chartLabel = entropies.map(e => `${e.label}: ${(e.value * 8).toFixed(2)} bits per byte`).join(', ');
      chart.setAttribute('aria-label', `Shannon entropy comparison. ${chartLabel}`);

      // Randomness pixel grids: real HMAC_DRBG bytes vs a deliberately-broken
      // LCG. Both are painted from actual byte streams — nothing is faked.
      // The grid needs 64*64 = 4096 bytes; draw a dedicated real stream so the
      // stats above keep running on their own 1024-byte samples.
      const gridState = await hmacDrbgInstantiate(getRandomEntropy(32), getRandomEntropy(16));
      const gridResult = await hmacDrbgGenerate(gridState, 64 * 64);
      paintGrid(section.querySelector<HTMLCanvasElement>('#pixel-drbg'), gridResult.output);
      paintGrid(section.querySelector<HTMLCanvasElement>('#pixel-lcg'), lcgBytes(64 * 64));

      resultsDiv.style.display = '';

      // Simulated Dual_EC_DRBG — use crypto.getRandomValues (statistically clean)
      // This demonstrates that even backdoored output passes statistical tests
      const dualEcBytes = getRandomEntropy(TEST_BYTES);
      const dualEcTests = runAllTests(dualEcBytes);

      const dualecTbody = section.querySelector<HTMLElement>('#dualec-tbody')!;
      dualecTbody.innerHTML = '';
      for (const test of dualEcTests) {
        const tr = document.createElement('tr');
        tr.innerHTML = `
          <td>${test.name}</td>
          <td>${test.pValue}</td>
          <td class="${test.passed ? 'stat-pass' : 'stat-fail'}">${test.passed ? 'PASS ✓' : 'FAIL ✗'}</td>
        `;
        dualecTbody.appendChild(tr);
      }
      dualecPanel.style.display = '';

      announce('Statistical tests complete — all DRBGs pass, including simulated Dual_EC');
    } finally {
      runBtn.disabled = false;
      runBtn.textContent = 'Test All Three DRBGs';
    }
  });
}
